pipeline {
    agent any 
    stages {
        stage('Code_Checkout') {
            steps {
                git 'https://github.com/bajisyed/simple-java-maven-app.git'
                echo 'checkout is completedd......'
            }
        } 
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
