pipeline {
    agent any
    try {
notifyStarted()
   stages {              
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
	    }
            post {
            	always {
                	junit 'target/surefire-reports/*.xml'
            	}
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
notifySuccessful()
} catch (e) {
currentBuild.result = "FAILED"
notifyFailed()
throw e

    }
}

def notifyStarted(){
    emailext body: '', subject: 'Build Started', to: 'manjunath.ramareddy@mindtree.com, baji.syed@mindtree.com'
}
def notifySuccessful(){
    emailext body: '', subject: 'Build Successful', to: 'manjunath.ramareddy@mindtree.com, baji.syed@mindtree.com'
}
def notifyFailed(){
    emailext body: '', subject: 'Build Failed', to: 'manjunath.ramareddy@mindtree.com, baji.syed@mindtree.com'
}
